export enum ServiceNames {
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  MERCHANT_SERVICE = 'MERCHANT_SERVICE',
  EXPERIENCE_SERVICE = 'EXPERIENCE_SERVICE',
  TICKET_SERVICE = 'TICKET_SERVICE',
  ORDER_SERVICE = 'ORDER_SERVICE',
  CART_SERVICE = 'CART_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
  PAYMENT_SERVICE = 'PAYMENT_SERVICE',
  PASS_SERVICE = 'PASS_SERVICE',
  ASSET_SERVICE = 'ASSET_SERVICE',
  KAFKA_SERVICE = 'KAFKA_SERVICE',
}
