export enum CartPatterns {
  GET_CART_BY_AUTH_ID = 'GET_CART_BY_AUTH_ID',
  CHECKOUT_BY_AUTH_ID = 'CHECKOUT_BY_AUTH_ID',
  ADD_ITEM_TO_CART_BY_AUTH_ID = 'ADD_ITEM_TO_CART_BY_AUTH_ID',
  REMOVE_ITEM_FROM_CART_BY_AUTH_ID = 'REMOVE_ITEM_FROM_CART_BY_AUTH_ID',
}
