export enum OrderPatterns {
  GET_ORDER = 'GET_ORDER',
  LIST_ORDERS = 'LIST_ORDERS',
  LIST_ORDERS_FOR_CUSTOMER = 'LIST_ORDERS_FOR_CUSTOMER',
  GET_ORDER_FOR_CUSTOMER = 'GET_ORDER_FOR_CUSTOMER',
  DELETE_ORDER = 'DELETE_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  GET_ORDER_WITH_CUSTOMER = 'GET_ORDER_WITH_CUSTOMER',
  GET_ORDER_WITH_CUSTOMER_FOR_MERCHANT = 'GET_ORDER_WITH_CUSTOMER_FOR_MERCHANT',
  LIST_ORDERS_FOR_MERCHANT = 'LIST_ORDERS_FOR_MERCHANT',
  FULFILL_ORDER = 'FULFILL_ORDER',
  FAIL_ORDER = 'FAIL_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
}
